### ISSUE TITLE
English pronounciation

### ISSUE THREAD

**Issue by HisMaj3sty** [SergeiSa/Control-Theory-Slides-Spring-2021#7]
Please excuse me for these nitpicks, but resolving these issues would make lectures a bit more acoustically pleasing

According to [the Oxford dictionary](https://www.oxfordlearnersdictionaries.com/definition/english/write) word *"write"* is pronounced as /raɪt/.  Letter *"w"* **is silent** and **not pronounced** as *"v"*

In addition, word *"annihilate"* is pronounced as /əˈnʌɪɪleɪt/ which means that *"h"* **is silent**

Also *"pseudoinverse"* should be pronounced as /ˈsjuːdəʊ/ meaning *"p"* **is silent**

**Comment by DCNick3** [comment]
Also, *"wrong"* should be pronounced like rŏng. Letter *"w"* **is silent** and **not pronounced** as *"v"*

**Comment by SergeiSa** [comment]
That is all true =) But no promises, when delivering a class it is hard to pay attention to pronunciation. Thanks for the reminders though!
